apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: wave-app-config 
  namespace: default 
  annotations: 
    argocd.argoproj.io/sync-wave: "1" 
data: 
  nginx.conf: | 
    server { 
      listen 80; 
      server_name localhost; 
      location / { 
        root /usr/share/nginx/html; 
        index index.html; 
      } 
    } 
