apiVersion: batch/v1 
kind: Job 
metadata: 
  name: wave-app-presync 
  namespace: default 
  annotations: 
    argocd.argoproj.io/hook: PreSync 
    argocd.argoproj.io/sync-wave: "0" 
spec: 
  template: 
    spec: 
      containers: 
      - name: presync 
        image: alpine:3.18 
        command: ["/bin/sh", "-c"] 
        args: ["echo 'Starting sync for wave-app application'"] 
      restartPolicy: Never 
  backoffLimit: 1 
