apiVersion: v1 
kind: Service 
metadata: 
  name: wave-app 
  namespace: default 
  annotations: 
    argocd.argoproj.io/sync-wave: "3" 
spec: 
  type: NodePort 
  ports: 
  - port: 80 
    targetPort: 80 
    nodePort: 30085 
  selector: 
    app: wave-app 
